public class Server {
    public static final String  FB_HOST             = 'new.facebook.com';
    public static final String  REST_URL            = 'http://api.' + FB_HOST + '/restserver.php';
    public static final String  SECURE_REST_URL     = 'https://api.' + FB_HOST + '/restserver.php';
    public static final String  API_VERSION         = '1.0';
    public static final String  LOGIN_URL           = 'http://www.' + FB_HOST + '/login.php';
    public static final String  SECURE_LOGIN_URL    = 'https://login.' + FB_HOST + '/login.php';
    public static final String  LOGOUT_URL          = 'http://www.' + FB_HOST + '/logout.php';
    public static final String  INSTALL_URL         = 'http://www.' + FB_HOST + '/install.php';
}